<?php

use App\Models\Plate;

return [
    "orders_plates" => [
        /* recover the price */
        [
            "order_id" => 1,
            "plate_id" => 6,
            "plate_price" => 18.00,
            "plate_quantity" => 1,
        ],

        [
            "order_id" => 1,
            "plate_id" => 2,
            "plate_price" => 9.50,
            "plate_quantity" => 3,
        ],

        [
            "order_id" => 1,
            "plate_id" => 1,
            "plate_price" => 8.00,
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 1,
            "plate_id" => 8,
            "plate_price" => 8.00,
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 1,
            "plate_id" => 3,
            "plate_price" => 6.00,
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 1,
            "plate_id" => 5,
            "plate_price" => 5.00,
            "plate_quantity" => 3,
        ],
        [
            "order_id" => 1,
            "plate_id" => 4,
            "plate_price" => 9.00,
            "plate_quantity" => 2,
        ],

        [
            "order_id" => 2,
            "plate_id" => 4,
            "plate_price" => 10.20,
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 2,
            "plate_id" => 7,
            "plate_price" => 6.00,
            "plate_quantity" => 3,
        ],
        [
            "order_id" => 3,
            "plate_id" => 2,
            "plate_price" => 9.50,
            "plate_quantity" => 4,
        ],
        [
            "order_id" => 3,
            "plate_id" => 1,
            "plate_price" => 20.00,
            "plate_quantity" => 1,
        ],

        [
            "order_id" => 4,
            "plate_id" => 4,
            "plate_price" => 9.50,
            "plate_quantity" => 3,
        ],

        [
            "order_id" => 5,
            "plate_id" => 6,
            "plate_price" => 7.00,
            "plate_quantity" => 1,
        ],

        [
            "order_id" => 5,
            "plate_id" => 14,
            "plate_price" => 11.50,
            "plate_quantity" => 3,
        ],

        [
            "order_id" => 6,
            "plate_id" => 4,
            "plate_price" => 3.50,
            "plate_quantity" => 4,
        ],

        [
            "order_id" => 7,
            "plate_id" => 8,
            "plate_price" => 15.50,
            "plate_quantity" => 3,
        ],
        [
            "order_id" => 7,
            "plate_id" => 5,
            "plate_price" => 15.50,
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 8,
            "plate_id" => 1,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 8,
            "plate_id" => 7,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 8,
            "plate_id" => 8,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 9,
            "plate_id" => 5,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 4,
        ],
        [
            "order_id" => 9,
            "plate_id" => 6,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 3,
        ],
        [
            "order_id" => 9,
            "plate_id" => 4,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 10,
            "plate_id" => 3,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 6,
        ],
        [
            "order_id" => 10,
            "plate_id" => 4,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 4,
        ],
        [
            "order_id" => 10,
            "plate_id" => 6,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 4,
        ],
        [
            "order_id" => 11,
            "plate_id" => 2,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 11,
            "plate_id" => 1,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 11,
            "plate_id" => 5,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 12,
            "plate_id" => 4,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 12,
            "plate_id" => 1,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 13,
            "plate_id" => 1,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 13,
            "plate_id" => 2,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 13,
            "plate_id" => 5,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 13,
            "plate_id" => 6,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 13,
            "plate_id" => 5,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 14,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 14,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 14,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 15,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 16,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 16,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 16,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 16,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 17,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 17,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 18,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 18,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 18,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 19,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 19,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 20,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 20,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 20,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 20,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 21,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 21,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 22,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 23,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 23,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 23,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 23,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 24,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 24,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 24,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 25,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 25,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 26,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 27,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 27,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 27,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 27,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 27,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 28,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 28,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 28,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 29,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 29,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 30,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 31,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 31,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 31,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 31,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 31,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 32,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 32,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 33,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 33,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 33,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 34,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 34,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 35,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 35,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 35,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 36,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 38,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 38,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 39,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 39,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 39,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 39,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 40,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 40,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 41,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 41,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 41,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 41,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 42,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 42,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 42,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 42,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 42,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 43,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 43,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 44,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 44,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 44,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 45,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 45,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 45,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 46,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 46,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 46,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 46,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 48,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 49,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 49,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 49,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 49,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 50,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 50,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 51,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 51,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 51,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 52,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 52,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 52,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 53,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 53,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 53,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 53,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 54,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 55,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 55,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 55,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 56,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 56,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 57,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 58,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 58,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 58,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 59,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 59,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 59,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 59,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 60,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 60,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 61,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 61,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 61,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 61,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 62,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 62,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],[
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 64,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 64,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 65,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 65,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 65,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 65,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 66,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 66,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 66,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 67,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 67,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 68,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 68,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 68,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 69,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 69,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 69,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 69,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 69,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 71,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 71,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 71,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 71,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 71,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 72,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 72,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 72,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 72,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 73,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 73,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 73,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 74,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 74,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 74,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 74,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 75,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 75,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 76,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 77,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 77,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 78,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 78,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 78,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 79,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 79,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 79,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 79,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 80,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 80,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 80,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 80,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 81,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 81,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 81,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 81,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 82,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 82,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 82,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 83,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 83,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 83,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 83,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 85,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 85,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 85,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 86,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 86,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 87,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 87,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 87,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 88,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 88,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 88,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 89,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 90,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 90,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 90,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 91,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 91,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 91,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 92,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 92,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 93,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 93,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 93,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 93,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 93,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 94,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 94,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 94,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],[
            "order_id" => 95,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 95,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 95,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 96,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 96,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 96,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 97,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 97,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 97,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 97,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 97,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 98,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 98,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 98,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 99,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 99,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 99,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 100,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 100,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 101,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 102,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 102,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 103,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 103,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 104,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 105,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 105,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 106,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 106,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 106,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 107,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 107,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 107,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 108,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 108,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 108,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 109,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 109,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 109,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 109,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 110,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 110,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 110,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 110,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 111,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 111,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 111,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 111,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 112,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 112,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 113,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 113,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 113,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 114,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 114,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 114,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 115,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 115,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 116,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 116,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 117,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 117,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 117,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 118,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 119,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 120,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 121,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 121,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 122,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 122,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 122,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 123,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 124,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 124,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 124,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 125,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 125,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 126,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 126,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 126,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 127,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 127,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 128,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 128,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 129,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 130,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 130,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 131,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 131,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 131,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 132,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 132,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 132,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 133,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 133,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 134,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 134,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 135,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 135,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 135,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 136,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 136,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 136,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 137,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 137,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 138,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 138,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 138,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 139,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 139,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 139,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 140,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 140,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 141,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 141,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 142,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 143,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 143,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 144,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 144,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 145,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 145,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 145,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 146,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 146,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 147,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 147,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 148,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 149,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 149,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 149,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 150,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 150,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 150,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 151,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 151,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 151,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 152,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 152,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 152,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 152,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 152,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 153,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 153,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 153,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 154,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 154,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 155,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 156,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 156,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 156,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 157,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 157,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 158,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 158,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 158,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 159,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 159,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 160,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 161,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 161,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 162,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 162,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 162,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 163,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 164,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 164,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 164,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 165,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 165,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 165,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 166,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 166,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 166,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 167,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 167,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 167,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 168,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 168,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 168,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 168,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 168,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 168,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 169,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 169,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 169,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 170,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 170,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 171,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 171,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 172,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 172,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 172,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 173,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 174,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 174,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 175,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 175,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 175,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 176,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 176,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 176,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 176,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 177,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 177,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 177,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 178,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 178,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 178,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 179,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 179,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 179,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 179,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 180,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 181,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 181,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 182,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 182,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 182,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 183,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 183,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 183,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 183,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 184,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
    ]
]; //arrivare a 184
