<?php

use App\Models\Plate;

return [
    "orders_plates" => [
        /* recover the price */
        [
            "order_id" => 1,
            "plate_id" => 6,
            "plate_price" => 18.00,
            "plate_quantity" => 1,
        ],

        [
            "order_id" => 1,
            "plate_id" => 2,
            "plate_price" => 9.50,
            "plate_quantity" => 3,
        ],

        [
            "order_id" => 1,
            "plate_id" => 1,
            "plate_price" => 8.00,
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 1,
            "plate_id" => 8,
            "plate_price" => 8.00,
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 1,
            "plate_id" => 3,
            "plate_price" => 6.00,
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 1,
            "plate_id" => 5,
            "plate_price" => 5.00,
            "plate_quantity" => 3,
        ],
        [
            "order_id" => 1,
            "plate_id" => 4,
            "plate_price" => 9.00,
            "plate_quantity" => 2,
        ],

        [
            "order_id" => 2,
            "plate_id" => 4,
            "plate_price" => 10.20,
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 2,
            "plate_id" => 7,
            "plate_price" => 6.00,
            "plate_quantity" => 3,
        ],
        [
            "order_id" => 3,
            "plate_id" => 2,
            "plate_price" => 9.50,
            "plate_quantity" => 4,
        ],
        [
            "order_id" => 3,
            "plate_id" => 1,
            "plate_price" => 20.00,
            "plate_quantity" => 1,
        ],

        [
            "order_id" => 4,
            "plate_id" => 4,
            "plate_price" => 9.50,
            "plate_quantity" => 3,
        ],

        [
            "order_id" => 5,
            "plate_id" => 6,
            "plate_price" => 7.00,
            "plate_quantity" => 1,
        ],

        [
            "order_id" => 5,
            "plate_id" => 14,
            "plate_price" => 11.50,
            "plate_quantity" => 3,
        ],

        [
            "order_id" => 6,
            "plate_id" => 4,
            "plate_price" => 3.50,
            "plate_quantity" => 4,
        ],

        [
            "order_id" => 7,
            "plate_id" => 8,
            "plate_price" => 15.50,
            "plate_quantity" => 3,
        ],
        [
            "order_id" => 7,
            "plate_id" => 5,
            "plate_price" => 15.50,
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 8,
            "plate_id" => 1,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 8,
            "plate_id" => 7,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 8,
            "plate_id" => 8,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 9,
            "plate_id" => 5,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 4,
        ],
        [
            "order_id" => 9,
            "plate_id" => 6,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 3,
        ],
        [
            "order_id" => 9,
            "plate_id" => 4,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 10,
            "plate_id" => 3,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 6,
        ],
        [
            "order_id" => 10,
            "plate_id" => 4,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 4,
        ],
        [
            "order_id" => 10,
            "plate_id" => 6,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 4,
        ],
        [
            "order_id" => 11,
            "plate_id" => 2,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 11,
            "plate_id" => 1,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 11,
            "plate_id" => 5,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 12,
            "plate_id" => 4,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 12,
            "plate_id" => 1,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 13,
            "plate_id" => 1,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 13,
            "plate_id" => 2,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 13,
            "plate_id" => 5,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 13,
            "plate_id" => 6,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 1,
        ],
        [
            "order_id" => 13,
            "plate_id" => 5,
            "plate_price" => rand(5, 15),
            "plate_quantity" => 2,
        ],
        [
            "order_id" => 14,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 14,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 14,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 15,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 16,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 16,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 16,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 16,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 17,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 17,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 18,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 18,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 18,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 19,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 19,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 20,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 20,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 20,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 20,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 21,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 21,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 22,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 23,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 23,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 23,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 23,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 24,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 24,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 24,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 25,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 25,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 26,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 27,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 27,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 27,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 27,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 27,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 28,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 28,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 28,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 29,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 29,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 30,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 31,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 31,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 31,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 31,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 31,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 32,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 32,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 33,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 33,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 33,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 34,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 34,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 35,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 35,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 35,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 36,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 38,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 38,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 39,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 39,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 39,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 39,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 40,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 40,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 41,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 41,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 41,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 41,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 42,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 42,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 42,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 42,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 42,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 43,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 43,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 44,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 44,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 44,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 45,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 45,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 45,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 46,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 46,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 46,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 46,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 47,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 48,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 49,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 49,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 49,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 49,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 50,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 50,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 51,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 51,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 51,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 52,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 52,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 52,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 53,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 53,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 53,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 53,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 54,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 55,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 55,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 55,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 56,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 56,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 57,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 58,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 58,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 58,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 59,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 59,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 59,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 59,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 60,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 60,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 61,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 61,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 61,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 61,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 62,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 62,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],[
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 63,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 64,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 64,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 65,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 65,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 65,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 65,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 66,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 66,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 66,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 67,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 67,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 68,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 68,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 68,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 69,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 69,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 69,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 69,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 69,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 70,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 71,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 71,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 71,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 71,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 71,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 72,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 72,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 72,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 72,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 73,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 73,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 73,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 74,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 74,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 74,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 74,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 75,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 75,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 76,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 77,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 77,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 78,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 78,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 78,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 79,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 79,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 79,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 79,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 80,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 80,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 80,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 80,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 81,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 81,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 81,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 81,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 82,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 82,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 82,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 83,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 83,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 83,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 83,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
        [
            "order_id" => 84,
            "plate_id" => rand(1, 8),
            "plate_price" => rand(5, 15),
            "plate_quantity" => rand(1, 6),
        ],
    ]
];
