<?php
return [
    'plates' => [
        [
            'restaurant_id' => '1',
            'name' => 'Tagliere di salumi',
            'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/10/come-comporre-tagliere-formaggi.jpg',
            'description' => 'Ingredienti: varietà di salumi.',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Caprese',
            'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2012/04/insalata-caprese-4.jpg',
            'description' => 'Ingredienti: mozzarella di bufala, pomodoro, basilico.',
            'price' => '9.50',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Spaghetti cacio e pepe',
            'image' => 'https://www.casapappagallo.it/storage/17060/cacio-e-pepe.jpg',
            'description' => 'Ingredienti: spaghetti, parmiggiano, pepe.',
            'price' => '12.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Rigatoni alla carbonara',
            'image' => 'https://pastafelice.it/cdn/shop/articles/Screenshot_20230219-030001_Chrome.jpg?v=1676772750',
            'description' => 'ingredienti: rigatoni, uovo, guangiale.',
            'price' => '13.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Pappardelle al ragù di cinghiale',
            'image' => 'https://cdn.cook.stbm.it/thumbnails/ricette/143/143867/hd750x421.jpg',
            'description' => 'Ingredienti: pappardelle, ragù di cinghiale.',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Spagetti con le vongole',
            'image' => 'https://www.giallozafferano.it/images/219-21925/Spaghetti-alle-vongole_650x433_wm.jpg',
            'description' => 'Ingredienti: spaghetti, vongole, aglio, prezzemolo.',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Tagliata di manzo',
            'image' => 'https://www.arezzonotizie.it/~media/horizontal-hi/34339515793082/tagliata-toscana-villa-campestri-olive-oil-resort-2.jpeg',
            'description' => 'Ingredienti: carne di manzo.',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Frittura di calamari',
            'image' => 'https://www.giallozafferano.it/images/153-15363/Frittura-di-calamari_780x520_wm.jpg',
            'description' => 'Ingredienti: calamari.',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Ravioli al vapore',
            'image' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2017/06/ravioli-di-carne-al-vapore-640x480.jpg',
            'description' => 'Ingredienti: farina, carne di bovino e vitello, carota, cipolla, verza.',
            'price' => '5.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Involtini primavera',
            'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/02/Involtiniprimavera.jpg',
            'description' => 'Ingredienti: farina, cavolo cappuccio, cipolle, carote.',
            'price' => '4.50',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Nigiri di salmone',
            'image' => 'https://www.buttalapasta.it/wp-content/uploads/2023/03/nigiri-ricetta.jpg',
            'description' => 'Ingredienti: riso, salmone.',
            'price' => '4.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Nigiri di tonno',
            'image' => 'https://www.sosushiandsound.it/wp-content/uploads/2023/04/nigiri-tonno-maguro-2.jpg',
            'description' => 'Ingredienti: riso, tonno.',
            'price' => '4.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Sashimi di salmone',
            'image' => 'https://d2j6dbq0eux0bg.cloudfront.net/images/28198052/1497211561.jpg',
            'description' => 'Ingredienti: salmone.',
            'price' => '4.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Sashimi di tonno',
            'image' => 'https://d2j6dbq0eux0bg.cloudfront.net/images/28198052/1497221598.jpg',
            'description' => 'Ingredienti: tonno.',
            'price' => '4.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Osomaki di salmone',
            'image' => 'https://san-sushi.it/wp-content/uploads/2022/07/050-Hosomaki-salmone-min-scaled.jpg',
            'description' => 'Ingredienti: riso, salmone, alga nori.',
            'price' => '5.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Osomaki di tonno',
            'image' => 'https://san-sushi.it/wp-content/uploads/2022/07/052-Hosomaki-tonno-min-scaled.jpg',
            'description' => 'Ingredienti: riso, tonno, alga nori.',
            'price' => '5.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '3',
            'name' => 'Samosa',
            'image' => 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/samosa-recipe.jpg',
            'description' => 'Ingredienti: farina, patate, anacardi, cipolle, peperoncini, curcuma, pisellini, zenzero, aglio, cumino.',
            'price' => '7.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '3',
            'name' => 'Masala dosa',
            'image' => 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/masala-dosa-recipe.jpg',
            'description' => 'Ingredienti: patate, semi di senape, lenticchie, zenzero, cipolla, coriandolo, peperoncino.',
            'price' => '10.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '3',
            'name' => 'Pollo tandori',
            'image' => 'https://www.fattoincasadabenedetta.it/wp-content/uploads/2023/03/pollo-tandoori.jpg',
            'description' => 'Ingredienti: pollo, pasta tandori, curry, yogurt bianco, aglio, zenzero, limone.',
            'price' => '14.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '3',
            'name' => 'Bhel puri',
            'image' => 'https://vegecravings.com/wp-content/uploads/2018/06/Bhel-Puri-Recipe-Step-By-Step-Instructions-1024x973.jpg.webp',
            'description' => 'Ingredienti: riso, arachidi, ceci, cetriolo, patate, cipolla, pomodoro, limone, curcuma.',
            'price' => '12.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '3',
            'name' => 'Pollo tikka masala',
            'image' => 'https://www.giallozafferano.it/images/ricette/171/17176/foto_hd/hd650x433_wm.jpg',
            'description' => 'Ingredienti: pollo, yogurt greco, aglio, zenzero, paprika, cipolla, panna.',
            'price' => '14.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '3',
            'name' => 'Meetha paan',
            'image' => 'https://img-global.cpcdn.com/recipes/9783949c6b4fa92d/680x482cq70/meetha-paan-and-date-mukhwaas-recipe-main-photo.jpg',
            'description' => 'Ingredienti: foglia di betel, noce di areca, varietà di spezie.',
            'price' => '12.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '3',
            'name' => 'Naan',
            'image' => 'https://www.giallozafferano.it/images/200-20067/Naan_650x433_wm.jpg',
            'description' => 'Ingredienti: farina, yogurt bianco, lievito di birra.',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '3',
            'name' => "Biryani d'agnello",
            'image' => 'https://cdn.cook.stbm.it/thumbnails/ricette/5/5087/hd750x421.jpg',
            'description' => 'Ingredienti: agnello, yogurt, riso, burro, cipolle, zafferano, aglio.',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Margherita',
            'image' => 'https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg',
            'description' => 'Pomodoro, mozzarella',
            'price' => '6.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Napoli',
            'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/04/pizza-napoli.jpg?w=713&a=c&h=407',
            'description' => 'Pomodoro, mozzarella, acciugh, origano',
            'price' => '7.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Capricciosa',
            'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/04/pizza-capricciosa.jpg',
            'description' => 'Pomodoro, mozzarella, prosciutto, funghi, carciofi, olive, capperi',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Americana',
            'image' => '',
            'description' => 'Pomodoro, mozzarella, wurstel, patatine fritte',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Tonno e cipolle',
            'image' => 'https://primochef.it/wp-content/uploads/2022/03/SH_pizza_tonno_e_cipolla.jpg',
            'description' => 'Pomodoro, mozzarella, tonno, cipolle',
            'price' => '7.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => '4 Formaggi',
            'image' => 'https://blog.giallozafferano.it/zeroglutine/wp-content/uploads/2020/04/IMG_5544-720x411.jpg',
            'description' => 'Pomodoro, mozzarella, gorgonzola, grana, brie',
            'price' => '9.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Frutti di mare',
            'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2012/05/pizza-con-zafferano-e-frutti-di-mare.jpg',
            'description' => 'Pomodoro, frutti di mare',
            'price' => '10.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Delicata',
            'image' => 'https://www.unmondodisapori.it/wp-content/uploads/2017/10/pizza-delicata.jpg',
            'description' => 'Mozzarella, zucchine, crudo di Parma, pomodoro ciliegino',
            'price' => '9.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Pulled pork',
            'image' => 'https://www.trinity-rome.com/wp/wp-content/uploads/2023/06/foto_101-scaled-2.webp',
            'description' => 'Ingredienti: Maiale sfilacciato, salsa honey mustard, cipolla, cavolo rosso, pomodoro.',
            'price' => '12.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'American smoked burger',
            'image' => 'https://www.trinity-rome.com/wp/wp-content/uploads/2023/06/Black-Angus-Gourmet-Burger-L-1.webp',
            'description' => 'Ingredienti: manzo di scottona, pancetta, cipolle caramelate',
            'price' => '14.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Patatine fritte',
            'image' => 'https://www.beach-sea.it/wp-content/uploads/2020/07/patatine_fritte.jpg',
            'description' => 'Ingredienti: patate.',
            'price' => '5.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Hot dog',
            'image' => 'https://img.freepik.com/free-photo/classic-hot-dog-with-ketchup-mustard-sauce-isolated-white-background_123827-29747.jpg',
            'description' => 'Ingredienti: pane, wurstel.',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'The beast',
            'image' => 'https://img.freepik.com/premium-photo/macro-photo-hamburger-stone-rustic-pub-generative-ai_918839-5436.jpg',
            'description' => 'Ingredienti: carne di manzo, cipolla, cetriolini, lattuga, ceddar.',
            'price' => '13.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Onion rings',
            'image' => 'https://i.ytimg.com/vi/E-eS4mMMlmo/maxresdefault.jpg',
            'description' => 'Ingredienti: cipolla.',
            'price' => '5.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Arrosticini',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuvikMpvTtOXORZjfxqOppDMd5KUOhDFEQGA&s',
            'description' => 'Ingredienti: agnello.',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'IPA 1LT',
            'image' => 'https://store.gmaserigrafia.it/wp-content/uploads/2015/05/BAYERN05P_boccale-_birra_1_litro_gma_serigrafia_personalizzazioni.jpg',
            'description' => 'Ingredienti:',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '6',
            'name' => 'La carbonara',
            'image' => 'https://blog.giallozafferano.it/dulcisinforno/wp-content/uploads/2021/03/Carbonara-ricetta-5328.jpg',
            'description' => 'Ingredienti:',
            'price' => '10.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '6',
            'name' => 'La cacio e pepe',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFb0DgZDQ1tFvAnzK_OWPUCe1NM-eUudJCAA&s',
            'description' => 'Ingredienti:',
            'price' => '11.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '6',
            'name' => 'La gricia',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRywJvQscyU_7zJn3_tYCweIvWycJ-p1RgIWw&s',
            'description' => 'Ingredienti:',
            'price' => '10.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '6',
            'name' => 'Amatriciana',
            'image' => 'https://www.giallozafferano.it/images/219-21923/Spaghetti-all-Amatriciana_650x433_wm.jpg',
            'description' => 'Ingredienti:',
            'price' => '09.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '6',
            'name' => 'Arrabbiata',
            'image' => 'https://www.giallozafferano.it/images/236-23631/Penne-all-Arrabbiata_450x300.jpg',
            'description' => 'Ingredienti:',
            'price' => '09.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '6',
            'name' => 'Gnocchi alla romana',
            'image' => 'https://www.giallozafferano.com/images/228-22838/Gnocchi-alla-Romana_650x433_wm.jpg',
            'description' => 'Ingredienti:',
            'price' => '10.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '6',
            'name' => 'Fettuccine alla papalina',
            'image' => 'https://s6890.pcdn.co/wp-content/uploads/2009/07/Fettuccine-alla-papalina-2-1.jpg',
            'description' => 'Ingredienti:',
            'price' => '08.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '6',
            'name' => 'Aglio olio e peperoncino',
            'image' => 'https://www.ilcuoreinpentola.it/wp-content/uploads/2023/03/spaghetti-aglio-olio-e-peperoncino.jpeg',
            'description' => 'Ingredienti:',
            'price' => '09.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '7',
            'name' => 'Spaghetti alle vongole',
            'image' => 'https://media-assets.lacucinaitaliana.it/photos/620fbf6288f5a214a3ad3e28/1:1/pass/undefined',
            'description' => 'Ingredienti:',
            'price' => '17.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '7',
            'name' => 'Calamarata',
            'image' => 'https://www.tavolartegusto.it/wp/wp-content/uploads/2019/07/Calamarata.jpg',
            'description' => 'Ingredienti:',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '7',
            'name' => 'Spaghetti allo scoglio',
            'image' => 'https://www.davidezambelli.com/wp-content/uploads/2021/05/1B46CF37-1CFC-47B3-BB53-9FC7C67CB861.jpg',
            'description' => 'Ingredienti:',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '7',
            'name' => 'Spaghetti al nero di seppia',
            'image' => 'https://authenticfoodquest.com/wp-content/uploads/2022/04/SpaghettiAlNeroDiSeppiaSiciliana_AuthenticFoodQuest.jpg',
            'description' => 'Ingredienti:',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '7',
            'name' => "Pappardelle all'astice",
            'image' => 'https://orapesce.it/cdn/shop/articles/tagliolini-astice_1100x.jpg?v=1650380700',
            'description' => 'Ingredienti:',
            'price' => '20.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '7',
            'name' => 'Spaghetti zucchine e gamberi',
            'image' => 'https://www.giallozafferano.it/images/2-205/Linguine-gamberetti-zucchine-e-zafferano_360x300.jpg',
            'description' => 'Ingredienti:',
            'price' => '10.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '7',
            'name' => 'Conchiglioni zucchine e salmone',
            'image' => 'https://media-assets.lacucinaitaliana.it/photos/61fd21d6e25043a74fc5c18f/1:1/w_2560%2Cc_limit/Conchiglioni-con-salmone-zucchine-e-salsa-di-gamberi.jpg',
            'description' => 'Ingredienti:',
            'price' => '17.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '7',
            'name' => 'Paccheri ragù bianco di pesce',
            'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2021/03/paccheri-al-ragu%CC%80-di-pesce-bianco_-8-1200x675.jpg',
            'description' => 'Ingredienti:',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Green Tartat Burger',
            'image' => 'https://www.gardengourmet.it/sites/default/files/recipes/8cfb80bcee1fee838708af8a60977e7b_190226_GG_Grilled_Green_Incredible_Burger.jpg',
            'description' => 'Ingredienti:',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Red Burger',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsAu6tAQzPxeuGB8fBLYPlrgxIbK85zE93VQ&s',
            'description' => 'Ingredienti:',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Fish Burger',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTboLWpoBg6g3FEeSKLq7NdXZdeeVc9-RJWNw&s',
            'description' => 'Ingredienti:',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Cheese Burger',
            'image' => 'https://www.modernhoney.com/wp-content/uploads/2022/05/Double-Double-Cheeseburger-with-Fries-Recipe-500x500.jpg',
            'description' => 'Ingredienti:',
            'price' => '12.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Blue Burger',
            'image' => 'https://thumbs.dreamstime.com/b/hamburger-e-patate-fritte-gialli-blu-sul-bordo-di-legno-62981756.jpg',
            'description' => 'Ingredienti:',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Yellow Veggie',
            'image' => 'https://citynews-cibotoday.stgy.ovh/~media/horizontal-mid/12074334723436/lo-spicy-cecio-di-flower-burger-ph-michael-gardenia.jpeg',
            'description' => 'Ingredienti:',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Violet Burger',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC_8MWlCsnDWB-WagPaHhIyTSH67u3gFQbPQ&s',
            'description' => 'Ingredienti:',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Pink Burger',
            'image' => 'https://hips.hearstapps.com/hmg-prod/images/pink-chicken-grill-burger-on-wood-background-royalty-free-image-540568254-1559856370.jpg',
            'description' => 'Ingredienti:',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '8',
            'name' => 'Black Burger ',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSd99SX4rO4Zobi0dog87-25ayaOKbEFOnkxw&s',
            'description' => 'Ingredienti:',
            'price' => '12.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Orecchia di elefante',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTORs9cTfUqAzWSxxRu_OL819DGT1FL9VOAQ&s',
            'description' => 'Ingredienti:',
            'price' => '17.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Pappardelle alla bolognese',
            'image' => 'https://media-assets.lacucinaitaliana.it/photos/61fb130ae334e788eab040b9/1:1/pass/undefined',
            'description' => 'Ingredienti:',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Risotto alla zafferano',
            'image' => 'https://media-assets.lacucinaitaliana.it/photos/61fbdba12c2fe9743efe8a2a/3:2/w_449,h_300,c_limit/empty',
            'description' => 'Ingredienti:',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Gua bao',
            'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/03/Gua-bao-0D6A1765-1200x675.jpg',
            'description' => 'Ingredienti:',
            'price' => '12.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Chili con carne',
            'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/03/chili-con-carne-still-life-2-1200x675.jpg',
            'description' => 'Ingredienti:',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Empanadas',
            'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/05/empanadas-2-1-1200x675.jpg',
            'description' => 'Ingredienti:',
            'price' => '14.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Poke bowl di tonno',
            'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/08/Poke-bowl-foto-finale-1-1659527212821-1200x675.jpg',
            'description' => 'Ingredienti:',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '9',
            'name' => 'Cous cous di pollo',
            'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/06/cous-cous-alla-marocchina-finale-3-1200x675.jpg',
            'description' => 'Ingredienti:',
            'price' => '12.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Love salmon',
            'image' => 'https://res.cloudinary.com/tf-lab/image/upload/w_600,h_310,c_fill,g_auto:subject,q_auto,f_auto/restaurant/67667556-a330-4833-b3c5-b223490baf55/b73c7149-d87d-4147-93a4-e07e571fe264.jpg',
            'description' => 'Ingredienti:',
            'price' => '09.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Love tuna',
            'image' => 'https://res.cloudinary.com/tf-lab/image/upload/w_600,h_310,c_fill,g_auto:subject,q_auto,f_auto/restaurant/1d52bc52-5d91-4d07-870b-deab9204fbaf/e2b54f4d-e7a3-4b45-a341-82a9f429fa84.jpg',
            'description' => 'Ingredienti:',
            'price' => '09.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Veggie',
            'image' => 'https://res.cloudinary.com/tf-lab/image/upload/restaurant/11ff9dcc-7468-497a-a46c-6e52684f4950/99b8ea02-85ca-4754-a53f-2e11419e10be.jpg',
            'description' => 'Ingredienti:',
            'price' => '08.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Cream cheese ',
            'image' => 'https://as1.ftcdn.net/v2/jpg/02/89/01/00/1000_F_289010094_SmY71lXzQMp9Y0G6LbDMTSkzCObsteeB.jpg',
            'description' => 'Ingredienti:',
            'price' => '09.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Rainbow',
            'image' => 'https://san-sushi.it/wp-content/uploads/2022/07/037-Uramaki-rainbow-avocado-granchio-salmone-tonno-branzino-e-maionese-min-scaled.jpg',
            'description' => 'Ingredienti:',
            'price' => '10.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Ebiten',
            'image' => 'https://as1.ftcdn.net/v2/jpg/02/85/52/62/1000_F_285526205_Kh7ZD2dXABJ4hVZvwMJwfJvr3eebMZiX.jpg',
            'description' => 'Ingredienti:',
            'price' => '09.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Scallop',
            'image' => 'https://media-cdn.tripadvisor.com/media/photo-s/0e/3f/35/b3/uramaki-con-capesante.jpg',
            'description' => 'Ingredienti:',
            'price' => '10.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Branzino lover',
            'image' => 'https://degustalo.it/cdn/shop/products/BRANZINO_ROLL.jpg?v=1611662347',
            'description' => 'Ingredienti:',
            'price' => '08.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '10',
            'name' => 'Uramaki collection',
            'image' => 'https://www.firenzetoday.it/~media/horizontal-hi/5046432187947/nima-sushi-uramakeria-2.jpg',
            'description' => 'Ingredienti:',
            'price' => '30.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '11',
            'name' => 'Pollo tacos',
            'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2023/02/Tacos-di-pollo-foto-finale-1-1200x675.jpg',
            'description' => 'Ingredienti:tacos di mais, pollo, verdure grigliate, maionese, fagioli',
            'price' => '09.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '11',
            'name' => 'Grill tacos',
            'image' => 'https://winedharma.com/wine-dharma/uploads/2020/10/1490-tacos-di-pollo-ricetta-messicana-cucina-messicana-tacos-con-carne-e-verdure-ricetta-originale-messic.jpg',
            'description' => 'Ingredienti: tacos di mais, manzo alla griglia, verdie grigliate, cipolle, salsa BBQ',
            'price' => '09.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '11',
            'name' => 'Fajitas',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_x4ZQ1Y8m_0ZXGK1ySQun1nVkLJzlHu4w4w&s',
            'description' => 'Ingredienti: tortillas di grano, fagioli tex mex, peperoni, cipolla, salsa spicy',
            'price' => '09.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '11',
            'name' => 'Pozole',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxF9yRTixP_aV-2sSno9oY8IStFAK9c8D3OA&s',
            'description' => 'Ingredienti: maiale, mais, peperoncino, cipolla, lattuga,ravanelli ',
            'price' => '10.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '11',
            'name' => 'Ceasar salad',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIAxieNe8cdfXwKfyZinIBviIZGUC8z37ZfA&s',
            'description' => 'Ingredienti: lattuga, pollo alla griglia, pomodori, avocado, salsa ceasar ',
            'price' => '08.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '11',
            'name' => 'Chilli',
            'image' => 'https://www.viaggi-usa.it/wp-content/uploads/2020/06/chili-con-carne-ricetta-originale-americana.jpg',
            'description' => 'Ingredienti: fagioli, peperoni, peperoncino',
            'price' => '11.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '11',
            'name' => 'Nachos',
            'image' => 'https://www.develey.it/wp-content/uploads/2018/11/nachos-con-salsa-al-formaggio.jpg',
            'description' => 'Ingredienti: nachos di mais, cheddar, formaggio fuso, fagioli, avocado, pomodoro, jalapeno, cipolla',
            'price' => '08.00',
            'is_visible' => '1',
        ]

    ]
];
