<?php
return [
    'plates' => [
        [
            'restaurant_id' => '1',
            'name' => 'Tagliere di salumi',
            'image' => 'https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2022/10/come-comporre-tagliere-formaggi.jpg',
            'description' => 'Ingredienti: varietà di salumi.',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Caprese',
            'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2012/04/insalata-caprese-4.jpg',
            'description' => 'Ingredienti: mozzarella di bufala, pomodoro, basilico.',
            'price' => '9.50',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => ' Spaghetti cacio e pepe',
            'image' => 'https://www.casapappagallo.it/storage/17060/cacio-e-pepe.jpg',
            'description' => 'Ingredienti: spaghetti, parmiggiano, pepe.',
            'price' => '12.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Rigatoni alla carbonara',
            'image' => 'https://pastafelice.it/cdn/shop/articles/Screenshot_20230219-030001_Chrome.jpg?v=1676772750',
            'description' => 'ingredienti: rigatoni, uovo, guangiale.',
            'price' => '13.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Pappardelle al ragù di cinghiale',
            'image' => 'https://cdn.cook.stbm.it/thumbnails/ricette/143/143867/hd750x421.jpg',
            'description' => 'Ingredienti: pappardelle, ragù di cinghiale.',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Spagetti con le vongole',
            'image' => 'https://www.giallozafferano.it/images/219-21925/Spaghetti-alle-vongole_650x433_wm.jpg',
            'description' => 'Ingredienti: spaghetti, vongole, aglio, prezzemolo.',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Tagliata di manzo',
            'image' => 'https://www.arezzonotizie.it/~media/horizontal-hi/34339515793082/tagliata-toscana-villa-campestri-olive-oil-resort-2.jpeg',
            'description' => 'Ingredienti: carne di manzo.',
            'price' => '18.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '1',
            'name' => 'Frittura di calamari',
            'image' => 'https://www.giallozafferano.it/images/153-15363/Frittura-di-calamari_780x520_wm.jpg',
            'description' => 'Ingredienti: calamari.',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Ravioli al vapore',
            'image' => 'https://cdn.ilclubdellericette.it/wp-content/uploads/2017/06/ravioli-di-carne-al-vapore-640x480.jpg',
            'description' => 'Ingredienti: farina, carne di bovino e vitello, carota, cipolla, verza.',
            'price' => '5.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Involtini primavera',
            'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/02/Involtiniprimavera.jpg',
            'description' => 'Ingredienti: farina, cavolo cappuccio, cipolle, carote.',
            'price' => '4.50',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Nigiri di salmone',
            'image' => 'https://www.buttalapasta.it/wp-content/uploads/2023/03/nigiri-ricetta.jpg',
            'description' => 'Ingredienti: riso, salmone.',
            'price' => '4.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Nigiri di tonno',
            'image' => 'https://www.sosushiandsound.it/wp-content/uploads/2023/04/nigiri-tonno-maguro-2.jpg',
            'description' => 'Ingredienti: riso, tonno.',
            'price' => '4.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Sashimi di salmone',
            'image' => 'https://d2j6dbq0eux0bg.cloudfront.net/images/28198052/1497211561.jpg',
            'description' => 'Ingredienti: salmone.',
            'price' => '4.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Sashimi di tonno',
            'image' => 'https://d2j6dbq0eux0bg.cloudfront.net/images/28198052/1497221598.jpg',
            'description' => 'Ingredienti: tonno.',
            'price' => '4.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Osomaki di salmone',
            'image' => 'https://san-sushi.it/wp-content/uploads/2022/07/050-Hosomaki-salmone-min-scaled.jpg',
            'description' => 'Ingredienti: riso, salmone, alga nori.',
            'price' => '5.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '2',
            'name' => 'Osomaki di tonno',
            'image' => 'https://san-sushi.it/wp-content/uploads/2022/07/052-Hosomaki-tonno-min-scaled.jpg',
            'description' => 'Ingredienti: riso, tonno, alga nori.',
            'price' => '5.00',
            'is_visible' => '1',
        ],[
            'restaurant_id' => '3',
            'name' => 'Samosa',
            'image' => 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/samosa-recipe.jpg',
            'description' => 'Ingredienti: farina, patate, anacardi, cipolle, peperoncini, curcuma, pisellini, zenzero, aglio, cumino.',
            'price' => '7.00',
            'is_visible' => '1',
        ],[
            'restaurant_id' => '3',
            'name' => 'Masala dosa',
            'image' => 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/masala-dosa-recipe.jpg',
            'description' => 'Ingredienti: patate, semi di senape, lenticchie, zenzero, cipolla, coriandolo, peperoncino.',
            'price' => '10.00',
            'is_visible' => '1',
        ],[
            'restaurant_id' => '3',
            'name' => 'Pollo tandori',
            'image' => 'https://www.fattoincasadabenedetta.it/wp-content/uploads/2023/03/pollo-tandoori.jpg',
            'description' => 'Ingredienti: pollo, pasta tandori, curry, yogurt bianco, aglio, zenzero, limone.',
            'price' => '14.00',
            'is_visible' => '1',
        ],[
            'restaurant_id' => '3',
            'name' => 'Bhel puri',
            'image' => 'https://vegecravings.com/wp-content/uploads/2018/06/Bhel-Puri-Recipe-Step-By-Step-Instructions-1024x973.jpg.webp',
            'description' => 'Ingredienti: riso, arachidi, ceci, cetriolo, patate, cipolla, pomodoro, limone, curcuma.',
            'price' => '12.00',
            'is_visible' => '1',
        ],[
            'restaurant_id' => '3',
            'name' => 'Pollo tikka masala',
            'image' => 'https://www.giallozafferano.it/images/ricette/171/17176/foto_hd/hd650x433_wm.jpg',
            'description' => 'Ingredienti: pollo, yogurt greco, aglio, zenzero, paprika, cipolla, panna.',
            'price' => '14.00',
            'is_visible' => '1',
        ],[
            'restaurant_id' => '3',
            'name' => 'Meetha paan',
            'image' => 'https://img-global.cpcdn.com/recipes/9783949c6b4fa92d/680x482cq70/meetha-paan-and-date-mukhwaas-recipe-main-photo.jpg',
            'description' => 'Ingredienti: foglia di betel, noce di areca, varietà di spezie.',
            'price' => '12.00',
            'is_visible' => '1',
        ],[
            'restaurant_id' => '3',
            'name' => 'Naan',
            'image' => 'https://www.giallozafferano.it/images/200-20067/Naan_650x433_wm.jpg',
            'description' => 'Ingredienti: farina, yogurt bianco, lievito di birra.',
            'price' => '8.00',
            'is_visible' => '1',
        ],[
            'restaurant_id' => '3',
            'name' => "Biryani d'agnello",
            'image' => 'https://cdn.cook.stbm.it/thumbnails/ricette/5/5087/hd750x421.jpg',
            'description' => 'Ingredienti: agnello, yogurt, riso, burro, cipolle, zafferano, aglio.',
            'price' => '15.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Margherita',
            'image' => 'https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg',
            'description' => 'Pomodoro, mozzarella',
            'price' => '6.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Napoli',
            'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/04/pizza-napoli.jpg?w=713&a=c&h=407',
            'description' => 'Pomodoro, mozzarella, acciugh, origano',
            'price' => '7.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Capricciosa',
            'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2019/04/pizza-capricciosa.jpg',
            'description' => 'Pomodoro, mozzarella, prosciutto, funghi, carciofi, olive, capperi',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Americana',
            'image' => '',
            'description' => 'Pomodoro, mozzarella, wurstel, patatine fritte',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Tonno e cipolle',
            'image' => 'https://primochef.it/wp-content/uploads/2022/03/SH_pizza_tonno_e_cipolla.jpg',
            'description' => 'Pomodoro, mozzarella, tonno, cipolle',
            'price' => '7.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => '4 Formaggi',
            'image' => 'https://blog.giallozafferano.it/zeroglutine/wp-content/uploads/2020/04/IMG_5544-720x411.jpg',
            'description' => 'Pomodoro, mozzarella, gorgonzola, grana, brie',
            'price' => '9.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Frutti di mare',
            'image' => 'https://wips.plug.it/cips/buonissimo.org/cms/2012/05/pizza-con-zafferano-e-frutti-di-mare.jpg',
            'description' => 'Pomodoro, frutti di mare',
            'price' => '10.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '4',
            'name' => 'Delicata',
            'image' => 'https://www.unmondodisapori.it/wp-content/uploads/2017/10/pizza-delicata.jpg',
            'description' => 'Mozzarella, zucchine, crudo di Parma, pomodoro ciliegino',
            'price' => '9.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Pulled pork',
            'image' => 'https://www.trinity-rome.com/wp/wp-content/uploads/2023/06/foto_101-scaled-2.webp',
            'description' => 'Ingredienti: Maiale sfilacciato, salsa honey mustard, cipolla, cavolo rosso, pomodoro.',
            'price' => '12.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'American smoked burger',
            'image' => 'https://www.trinity-rome.com/wp/wp-content/uploads/2023/06/Black-Angus-Gourmet-Burger-L-1.webp',
            'description' => 'Ingredienti: manzo di scottona, pancetta, cipolle caramelate',
            'price' => '14.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Patatine fritte',
            'image' => 'https://www.beach-sea.it/wp-content/uploads/2020/07/patatine_fritte.jpg',
            'description' => 'Ingredienti: patate.',
            'price' => '5.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Hot dog',
            'image' => 'https://img.freepik.com/free-photo/classic-hot-dog-with-ketchup-mustard-sauce-isolated-white-background_123827-29747.jpg',
            'description' => 'Ingredienti: pane, wurstel.',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'The beast',
            'image' => 'https://img.freepik.com/premium-photo/macro-photo-hamburger-stone-rustic-pub-generative-ai_918839-5436.jpg',
            'description' => 'Ingredienti: carne di manzo, cipolla, cetriolini, lattuga, ceddar.',
            'price' => '13.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Onion rings',
            'image' => 'https://i.ytimg.com/vi/E-eS4mMMlmo/maxresdefault.jpg',
            'description' => 'Ingredienti: cipolla.',
            'price' => '5.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'Arrosticini',
            'image' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuvikMpvTtOXORZjfxqOppDMd5KUOhDFEQGA&s',
            'description' => 'Ingredienti: agnello.',
            'price' => '8.00',
            'is_visible' => '1',
        ],
        [
            'restaurant_id' => '5',
            'name' => 'IPA 1LT',
            'image' => 'https://store.gmaserigrafia.it/wp-content/uploads/2015/05/BAYERN05P_boccale-_birra_1_litro_gma_serigrafia_personalizzazioni.jpg',
            'description' => 'Ingredienti:',
            'price' => '8.00',
            'is_visible' => '1',
        ],

    ]
];